### PR TITLE
deploy-files-service

### PR DESCRIPTION
**Pull request by Benedikt89**
Setup to deploy files service

### CODE REVIEW

**Comment by Benedikt89** [comment]
run build production files

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production files

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production files

**Comment by 8blank8** [comment]
run build production files

**Pull request merged**
