### PR TITLE
Db

### PR DESCRIPTION
**Pull request by 8blank8**
changes: 
 - added prisma 
 - added migration init 
 - added prisma manual routes

### CODE REVIEW

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by 8blank8** [comment]
run build production inctagram

**Comment by 8blank8** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production inctagram

**Comment by 8blank8** [comment]
run build production inctagram

**Comment by Benedikt89** [comment]
run build production files

**Pull request merged**
